### ISSUE TITLE
Icon by GNOME HIG

### ISSUE THREAD

**Issue by gargullia** [pablo-s/passes#14]

**Comment by pablo-s** [comment]
@gargullia when I created the icon, I followed (or tried to follow) the guidelines that you linked.
I know the icon is far from perfect... but the truth is that I am not an artist and until now I have not managed to make it better.
Do you have specific suggestions to be implemented?

**Comment by sonnyp** [comment]
Consider submitting passes to GNOME Circle - designers will have a look and can help.

https://circle.gnome.org/

**Comment by pablo-s** [comment]
Thanks @sonnyp , I will consider that possibility.
