### ISSUE TITLE
[Feature request] Add to GNOME Circle

### ISSUE THREAD

**Issue by werdahias** [pablo-s/passes#16]
I really like your software. Maybe you could look into applying for your app to be featured in GNOME circle; see circle.gnome.org. Let me know what you think.

**Comment by pablo-s** [comment]
Hello @werdahias ! Thanks a lot for your comment!  Currently, I think the application does not meet all requirements detailed in https://gitlab.gnome.org/Teams/Releng/AppOrganization/-/blob/main/AppCriteria.md. However, as soon as I correct them I will try to apply :)

**Comment by Ridhubharan** [comment]
If you add it to Gnome circle, it will be easier to find this app. I have been searching for this kind of app for so long and found it by dumb luck.
