### ISSUE TITLE
Add more info

### ISSUE THREAD

**Issue by airon90** [pablo-s/passes#2]
README lacks of some useful information:

1. How to build this app? which dependencies it needs?
2. How does it work? I tried to add a pkpass ticket and png file of QR code containing my EU Digital COVID Certificate's data but nothing happened

**Comment by pablo-s** [comment]
Hello @airon90 ,

I am creating this application using gnome-builder and I have not even tried to build it by myself without this IDE.  However, I think these links will answer your first two questions:

https://aur.archlinux.org/packages/passes
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=passes

About your last question, press the "plus" button and select a pkpass. Importing just images or other formats (such as PDFs or espass files) is not yet supported.

Did you see any error when you imported the pkpass? A toast should appear with an error if the file was not loaded.

**Comment by airon90** [comment]
Thank you for your answer. Please take a look at #3 so that you understand why I opened this bug report. I close this BR in order to open a new one for the second request.
