### ISSUE TITLE
How to add rewards cards or coupons?

### ISSUE THREAD

**Issue by Izaic** [pablo-s/passes#34]
I noticed it said on the flathub that it could work for rewards cards or coupons... The question is how? I imagine you'd use another app to scan the barcode and turn it into a file format readable by this app?

**Comment by pablo-s** [comment]
Hello @Izaic ,

Currently, Passes only support two formats: espass and pkpass.

If you have a reward card, coupon, boarding pass, etc in any of these formats, then you can press the button on the top left and import it.

If not, it is possible that there are ways to create a pkpsss that you can later import in the tool.

Adding some types of passes by scanning a barcode is a feature that I would like to add. However, I have not had time to do it yet.

Can I ask you where did you get the coupon or reward card?

**Comment by Izaic** [comment]
I have physical rewards cards I keep in my wallet, but I was hoping to be able to digitize them and use them on my Librem 5 with this app. I can't find a way to turn the rewards card barcodes into a espass or pkpass format however.

**Comment by pablo-s** [comment]
@Izaic

Sorry for the late response.

Sadly it is a feature that is not here yet, but I will try to include it soon.

In the meantime, perhaps you can use services such as https://www.passsource.com. They allow you to create and download pkpsss files.

I hope it helps.
