### ISSUE TITLE
QR code tiny

### ISSUE THREAD

**Issue by piegamesde** [pablo-s/passes#48]
For some reason, the QR code on my device is tiny with no way to make it larger

![image](https://github.com/pablo-s/passes/assets/14054505/c076f0f4-cdb6-43e1-8034-b7d44fec1664)

Screen size: 2560 × 1600
Display scaling: 1.5
Font scaling: 1.1
Compositor: GNOME Mutter

**Comment by pablo-s** [comment]
Hi @piegamesde !

Have you tried clicking on the code? It is actually a button that should show you a larger version of it.

**Comment by piegamesde** [comment]
Yes. I get a toast error message `'NoneType' object has no attribute 'barcodes'`

**Comment by piegamesde** [comment]
I am on NixOS, and can reproduce both with the Flatpak and the Nix packaging. Both version 0.9. I'll see if I can strip the pass

**Comment by pablo-s** [comment]
@piegamesde , are you still having this problem?

If you are still interested, please send me the pass (remember you can unzip the pass and remove any information you do not want to share).

**Comment by piegamesde** [comment]
Oh well, I forgot. I just tried it again, and while I don't think I succeeded at properly, I found out that clicking on the QR code works as soon as there is more than one ticket in the app.

**Comment by pablo-s** [comment]
Ok! No problem!

Now that you have mentioned that the problem happens with just a single pass in the list... it is very likely that the issue has been already fixed (but not released).

It is a problem with the focus of the pass widget and it can be worked around if you click on the pass (on the pass list) and then you click on the barcode button.

Anyway, thanks for spending time to report the issue!
