### ISSUE TITLE
Verify on Flathub

### ISSUE THREAD

**Issue by bragefuglseth** [pablo-s/passes#51]
The app is currently unverified on Flathub; have you considered verifying it?

**Comment by pablo-s** [comment]
Hi @bragefuglseth !

Yes, I have.

My problem is that I own the domain name, but I do not have a web hosting (and I do not want to pay for it).

Any suggestion? Do you know if there is another way of verifying in Flathub?

**Comment by bragefuglseth** [comment]
You can host the website with GitHub Pages! Just [connect your domain name to your own GitHub page](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site). I'm doing that myself, you can use [my setup](https://github.com/bragefuglseth/bragefuglseth.github.io) as a reference. (the verification stuff is in the .well-known folder). 

I'm available to answer any other questions that arise along the way.

**Comment by pablo-s** [comment]
I still have to do my personal web page... but Passes is now verified!
Thanks for your help!
