### ISSUE TITLE
Add support to dark mode

### ISSUE THREAD

**Issue by airon90** [pablo-s/passes#6]
Here you can find info about how to add support to dark mode: https://developer.gnome.org/documentation/tutorials/beginners/getting_started/dark_mode.html

**Comment by bragefuglseth** [comment]
I don’t think this is necessary for Passes as long as it follows the system color scheme. App-specific color scheme switchers should be for apps that are heavily focused on for longer periods of time, like text editors, where people might want to have it in a different color scheme from the system for contrast / eye strain reasons.

**Comment by pablo-s** [comment]
@bragefuglseth Thank you for your help again! It makes a lot of sense.
